{
 "title": "New dashboard",
 "time": { "from": "2024-10-02T23:43:21.067Z", "to": "2024-10-02T23:46:05.372Z" },
 "panels": [
  {
   "title": "Users Statistics",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT * FROM users " }
   ]
  },
  {
   "title": "User Text Statistics",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT * FROM user_texts " }
   ]
  },
  {
   "title": "Button Click Statistics",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT button_name, COUNT(*) AS mention_count\r\nFROM button_clicks\r\nGROUP BY button_name;\r\n"
    }
   ]
  },
  {
   "title": "User Activity Chart",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 8 },
   "targets": [
    { "rawSql": "SELECT * from button_clicks " }
   ]
  }
 ]
}